---
injectable:
   '@travetto/config': Config  
   '@travetto/di': 
      - Injectable
      - Application

application:
   '@travetto/di':
      - Application

injectable-factory:
   '@travetto/di':
      - InjectableFactory

inject:
   '@travetto/di': 
      - Inject